package co.global.fsfb.fsfbapi.constants;

public class QueryConst {

    public static class Citas {

        public static final String CONSULTAR_CITAS = "SELECT\n"
                + "DP.DVP_PRO_GLOSA \"ciudad\" ,\n"
                + "CIT.CG_ID_CITA_NUMERO \"id_cita\",\n"
                + "EC.EC_IDCODIGO \"cod estado_cita_ca_descripcion\",\n"
                + "EC.EC_DESCRIPCION \"estado_cita_ca_descripcion\",\n"
                + "CIT.CG_ASISTENCIA \"asistencia\",\n"
                + "PAC.PAC_PAC_NUMERO \"pacNum\",\n"
                + "TRIM(PAC.PAC_PAC_NOMBRE)||' '||TRIM(PAC.PAC_PAC_APELLPATER)||' '||TRIM(PAC.PAC_PAC_APELLMATER) \"Nombre Completo\",\n"
                + "PAC.PAC_PAC_TIPOIDENTCODIGO \"Codigo Tipo de Documento\",\n"
                + "TIP.TIPIDAV \"Tipo de Documento homologado\",\n"
                + "PAC.PAC_PAC_RUT \"Documento\",\n"
                + "PAC.PAC_PAC_FONO \"Telefono\",\n"
                + "PAC.DONURL \"Correo Electronico\",\n"
                + "AGEND.PCA_AGE_HORACITAC \"Hora Cita\",\n"
                + "AGEND.PCA_AGE_FECHACITAC \"Fecha Cita\",\n"
                + "SER.SER_SER_CODIGO \"codigo servicio\",\n"
                + "SER.SER_SER_DESCRIPCIO \"Servicio\",\n"
                + "AGEND.PCA_AGE_CODIGPROFE \"codigo Profesional\",\n"
                + "AGEND.PCA_AGE_OBJETO \"Consultorio\",\n"
                + "PREST.PRE_PRE_CODIGO \"codigo Prestacion\",\n"
                + "PREST.PRE_PRE_DESCRIPCIO \"Prestacion\",\n"
                + "CA.CODIGOINTERNOCENTRO \"Codigo Centro Operativo\",\n"
                + "CA.NOMBRECENTROATEN \"Centro Operativo\",\n"
                + "CONV.CON_CON_CODIGO \"Codigo Convenio\",\n"
                + "CONV.CON_CON_DESCRIPCIO \"Convenio\",\n"
                + "AGEND.PCA_AGE_CODIGRECEP \"Codigo usuario\",\n"
                + "AGEND.PCA_AGE_FECHADIGIT \"Fecha de Asignacion\",\n"
                + "(SELECT MAX(DIRECCION) FROM admsalud.log_centrosatenc@ISIS DIR\n"
                + "WHERE CA.CODIGOINTERNOCENTRO =DIR.CODIGOINTERNOCENTRO ) \"Direccion Centro Operativo\",\n"
                + "CA.TELEFONO \"Telefono Centro Operativo\",\n"
                + "CA.DVP_PRO_CODIGO \"Ciudad\",\n"
                + "ESPE.SER_ESP_CODIGO \"Cod Especialidad\",\n"
                + "ESPE.SER_ESP_DESCRIPCIO \"Especialidad\",\n"
                + "SER.SER_SER_CODSUBESPE \"Cod subespecialidad\",\n"
                + "SUBESPE.SER_SUB_DESCRIPCIO \"Subespecialidad\",\n"
                + "funchspgetprof@isis(1,AGEND.PCA_AGE_CODIGPROFE) \"Profesional\",\n"
                + "admsalud.glbgetnomusr@isis(AGEND.PCA_AGE_CODIGRECEP) \"Usuario que asigna cita\",\n"
                + "(SELECT MAX(SER_LUG_UBICACION)\n"
                + "FROM ADMSALUD.SER_LUGARES@ISIS LUG,\n"
                + "ADMSALUD.SER_RECASISTEN@ISIS REC\n"
                + "WHERE OBJ.SER_OBJ_UBICACION = LUG.SER_LUG_CODIGO\n"
                + "AND OBJ.CODIGOCENTROATEN = LUG.CODIGOCENTROATEN\n"
                + "AND OBJ.SER_REC_TIPO = REC.SER_REC_TIPO\n"
                + "AND LUG.SER_LUG_TIPOLUGAR= REC.SER_REC_TIPOLUGAR) \"ubicacion\",\n"
                + "CA.CODIGOCENTROATEN \"Letra Codigo Centro Operativo\",\n"
                + "UBIC.UBICACION \"ubicacion sede\" ,\n"
                + "UBIC.DIRECCION \"direccion\" ,\n"
                + "CONV.CON_TIPOCONVECOD \"TipoConvenio\"\n"
                + "FROM ADMSALUD.PCA_AGENDA@ISIS AGEND\n"
                + "\n"
                + "INNER JOIN ADMSALUD.PAC_PACIENTE@ISIS PAC\n"
                + "ON AGEND.PCA_AGE_NUMERPACIE = PAC.PAC_PAC_NUMERO\n"
                + "\n"
                + "LEFT JOIN ADMSALUD.TAB_TIPOIDENT@ISIS TIP\n"
                + "ON PAC.PAC_PAC_TIPOIDENTCODIGO = TIP.TAB_TIPOIDENTCODIGO\n"
                + "\n"
                + "INNER JOIN ADMSALUD.SER_SERVICIOS@ISIS SER\n"
                + "ON AGEND.PCA_AGE_CODIGSERVI = SER.SER_SER_CODIGO\n"
                + "\n"
                + "LEFT JOIN ADMSALUD.SER_ESPECIALI@ISIS ESPE\n"
                + "ON ESPE.SER_ESP_CODIGO = SER.SER_SER_CODIGESPEC\n"
                + "\n"
                + "LEFT JOIN ADMSALUD.SER_SUBESPECIA@ISIS SUBESPE\n"
                + "ON SER.SER_SER_CODSUBESPE= SUBESPE.SER_SUB_CODIGO\n"
                + "AND SUBESPE.SER_ESP_CODIGO=ESPE.SER_ESP_CODIGO\n"
                + "\n"
                + "INNER JOIN ADMSALUD.RPA_FORCIT@ISIS FORCIT\n"
                + "ON AGEND.PCA_AGE_TIPOFORMU = FORCIT.RPA_FOR_TIPOFORMU\n"
                + "AND AGEND.PCA_AGE_NUMERFORMU = FORCIT.RPA_FOR_NUMERFORMU\n"
                + "AND AGEND.PCA_AGE_FECHACITAC = FORCIT.RPA_FCI_FECHACITAC\n"
                + "AND AGEND.PCA_AGE_HORACITAC = FORCIT.RPA_FCI_HORACITAC\n"
                + "\n"
                + "\n"
                + "LEFT JOIN ADMSALUD.CON_CONVENIO@ISIS CONV\n"
                + "ON FORCIT.CON_CON_CODIGO = CONV.CON_CON_CODIGO\n"
                + "\n"
                + "LEFT JOIN ADMSALUD.PRE_PRESTACION@ISIS PREST\n"
                + "ON FORCIT.PRE_PRE_CODIGO = PREST.PRE_PRE_CODIGO\n"
                + "\n"
                + "\n"
                + "LEFT JOIN ADMSALUD.TAB_CENTROSATENC@ISIS CA\n"
                + "ON AGEND.PCA_AGE_LUGAR= CA.CODIGOCENTROATEN\n"
                + "\n"
                + "\n"
                + "INNER JOIN ADMSALUD.SER_OBJETOS@ISIS OBJ\n"
                + "ON AGEND.PCA_AGE_TIPOOBJET = OBJ.SER_REC_TIPO\n"
                + "AND AGEND.PCA_AGE_OBJETO = OBJ.SER_OBJ_CODIGO\n"
                + "\n"
                + "\n"
                + "INNER JOIN CA_UBICACION_SEDES UBIC\n"
                + "ON AGEND.PCA_AGE_OBJETO = UBIC.CONSULTORIO\n"
                + "LEFT JOIN CA_CITAS_GESTIONADAS CIT\n"
                + "ON TRIM(AGEND.PCA_AGE_NUMERPACIE) = TRIM(CIT.PAC_PAC_NUMERO)\n"
                + "AND AGEND.PCA_AGE_FECHACITAC = CIT.PCA_AGE_FECHACITAC AND\n"
                + "AGEND.PCA_AGE_HORACITAC = CIT.PCA_AGE_HORACITAC\n"
                + "LEFT JOIN CA_ESTADOS_CITAS EC\n"
                + "ON CIT.EC_IDCODIGO = EC.EC_IDCODIGO\n"
                + "LEFT JOIN ADMSALUD.DVP_PROVINCIA@ISIS DP\n"
                + "ON CA.DVP_PRO_CODIGO = DP.DVP_PRO_CODIGO\n"
                + "\n"
                + "WHERE AGEND.PCA_AGE_FECHACITAC BETWEEN :FECHAINICIAL AND :FECHAFINAL";

        public static final String CONSULTAR_CITA_POR_ID
                = "SELECT\n"
                + "CIT.CG_ID_CITA_NUMERO \"id_cita\",\n"
                + "EC.EC_IDCODIGO \"cod estado_cita_ca_descripcion\",\n"
                + "EC.EC_DESCRIPCION \"estado_cita_ca_descripcion\",\n"
                + "CIT.CG_ASISTENCIA \"asistencia\",\n"
                + "PAC.PAC_PAC_NUMERO \"pacNum\",\n"
                + "TRIM(PAC.PAC_PAC_NOMBRE)||' '||TRIM(PAC.PAC_PAC_APELLPATER)||' '||TRIM(PAC.PAC_PAC_APELLMATER) \"Nombre Completo\",\n"
                + "PAC.PAC_PAC_TIPOIDENTCODIGO \"Codigo Tipo de Documento\",\n"
                + "TIP.TIPIDAV \"Tipo de Documento homologado\",\n"
                + "PAC.PAC_PAC_RUT \"Documento\",\n"
                + "PAC.PAC_PAC_FONO \"Telefono\",\n"
                + "PAC.DONURL \"Correo Electronico\",\n"
                + "AGEND.PCA_AGE_HORACITAC \"Hora Cita\",\n"
                + "AGEND.PCA_AGE_FECHACITAC \"Fecha Cita\",\n"
                + "SER.SER_SER_CODIGO \"codigo servicio\",\n"
                + "SER.SER_SER_DESCRIPCIO \"Servicio\",\n"
                + "AGEND.PCA_AGE_CODIGPROFE \"codigo Profesional\",\n"
                + "AGEND.PCA_AGE_OBJETO \"Consultorio\",\n"
                + "PREST.PRE_PRE_CODIGO \"codigo Prestacion\",\n"
                + "PREST.PRE_PRE_DESCRIPCIO \"Prestacion\",\n"
                + "CA.CODIGOINTERNOCENTRO \"Codigo Centro Operativo\",\n"
                + "CA.NOMBRECENTROATEN \"Centro Operativo\",\n"
                + "CONV.CON_CON_CODIGO \"Codigo Convenio\",\n"
                + "CONV.CON_CON_DESCRIPCIO \"Convenio\",\n"
                + "AGEND.PCA_AGE_CODIGRECEP \"Codigo usuario\",\n"
                + "AGEND.PCA_AGE_FECHADIGIT \"Fecha de Asignacion\",\n"
                + "(SELECT MAX(DIRECCION) FROM admsalud.log_centrosatenc@ISIS DIR\n"
                + "WHERE CA.CODIGOINTERNOCENTRO =DIR.CODIGOINTERNOCENTRO ) \"Direccion Centro Operativo\",\n"
                + "CA.TELEFONO \"Telefono Centro Operativo\",\n"
                + "CA.DVP_PRO_CODIGO \"Ciudad\",\n"
                + "ESPE.SER_ESP_CODIGO \"Cod Especialidad\",\n"
                + "ESPE.SER_ESP_DESCRIPCIO \"Especialidad\",\n"
                + "SER.SER_SER_CODSUBESPE \"Cod subespecialidad\",\n"
                + "SUBESPE.SER_SUB_DESCRIPCIO \"Subespecialidad\",\n"
                + "funchspgetprof@isis(1,AGEND.PCA_AGE_CODIGPROFE) \"Profesional\",\n"
                + "admsalud.glbgetnomusr@isis(AGEND.PCA_AGE_CODIGRECEP) \"Usuario que asigna cita\",\n"
                + "(SELECT MAX(SER_LUG_UBICACION) FROM ADMSALUD.SER_LUGARES@ISIS LUG, ADMSALUD.SER_RECASISTEN@ISIS REC "
                + "WHERE OBJ.SER_OBJ_UBICACION = LUG.SER_LUG_CODIGO "
                + "AND OBJ.CODIGOCENTROATEN = LUG.CODIGOCENTROATEN "
                + "AND  OBJ.SER_REC_TIPO = REC.SER_REC_TIPO "
                + "AND LUG.SER_LUG_TIPOLUGAR= REC.SER_REC_TIPOLUGAR) \"ubicacion\", \n"
                + "CA.CODIGOCENTROATEN \"Letra Codigo Centro Operativo\", \n"
                + "CONV.CON_TIPOCONVECOD \"TipoConvenio\" "
                + "FROM            ADMSALUD.PCA_AGENDA@ISIS AGEND\n"
                + "\n"
                + "INNER JOIN      ADMSALUD.PAC_PACIENTE@ISIS PAC\n"
                + "ON              TRIM(AGEND.PCA_AGE_NUMERPACIE)  = TRIM(PAC.PAC_PAC_NUMERO)\n"
                + "            \n"
                + "LEFT JOIN       ADMSALUD.TAB_TIPOIDENT@ISIS TIP"
                + "\n"
                + "ON              TRIM(PAC.PAC_PAC_TIPOIDENTCODIGO) = TRIM(TIP.TAB_TIPOIDENTCODIGO)\n"
                + "            \n"
                + "INNER JOIN      ADMSALUD.SER_SERVICIOS@ISIS SER"
                + "\n"
                + "ON              TRIM(AGEND.PCA_AGE_CODIGSERVI) = TRIM(SER.SER_SER_CODIGO)\n"
                + "\n"
                + "LEFT JOIN      ADMSALUD.SER_ESPECIALI@ISIS ESPE\n"
                + "ON             ESPE.SER_ESP_CODIGO = SER.SER_SER_CODIGESPEC\n"
                + "\n"
                + "LEFT JOIN      ADMSALUD.SER_SUBESPECIA@ISIS SUBESPE\n"
                + "ON             SER.SER_SER_CODSUBESPE= SUBESPE.SER_SUB_CODIGO\n"
                + "               AND SUBESPE.SER_ESP_CODIGO=ESPE.SER_ESP_CODIGO\n"
                + "\n"
                + "INNER JOIN      ADMSALUD.RPA_FORCIT@ISIS FORCIT\n"
                + "ON              TRIM(AGEND.PCA_AGE_TIPOFORMU) = TRIM(FORCIT.RPA_FOR_TIPOFORMU)\n"
                + "                AND TRIM(AGEND.PCA_AGE_NUMERFORMU) = TRIM(FORCIT.RPA_FOR_NUMERFORMU)\n"
                + "                AND TRIM(AGEND.PCA_AGE_FECHACITAC) = TRIM(FORCIT.RPA_FCI_FECHACITAC)\n"
                + "                AND TRIM(AGEND.PCA_AGE_HORACITAC) =  TRIM(FORCIT.RPA_FCI_HORACITAC)\n"
                + "                       \n"
                + "LEFT JOIN       ADMSALUD.CON_CONVENIO@ISIS CONV\n"
                + "ON              TRIM(FORCIT.CON_CON_CODIGO) = TRIM(CONV.CON_CON_CODIGO)\n\nLEFT JOIN       ADMSALUD.PRE_PRESTACION@ISIS PREST\nON              TRIM(FORCIT.PRE_PRE_CODIGO) = TRIM(PREST.PRE_PRE_CODIGO)\n\nLEFT JOIN       ADMSALUD.TAB_CENTROSATENC@ISIS CA \nON              TRIM(AGEND.PCA_AGE_LUGAR) = TRIM(CA.CODIGOCENTROATEN)\n\nINNER JOIN      ADMSALUD.SER_OBJETOS@ISIS OBJ\nON              TRIM(AGEND.PCA_AGE_TIPOOBJET) = TRIM(OBJ.SER_REC_TIPO)\n                AND TRIM(AGEND.PCA_AGE_OBJETO) = TRIM(OBJ.SER_OBJ_CODIGO)\n                \nLEFT JOIN      CA_CITAS_GESTIONADAS CIT\nON              TRIM(AGEND.PCA_AGE_NUMERPACIE)  = TRIM(CIT.PAC_PAC_NUMERO)\n                AND AGEND.PCA_AGE_FECHACITAC = CIT.PCA_AGE_FECHACITAC AND                 AGEND.PCA_AGE_HORACITAC = CIT.PCA_AGE_HORACITAC    \nLEFT JOIN      CA_ESTADOS_CITAS EC\nON              CIT.EC_IDCODIGO  = EC.EC_IDCODIGO \nWHERE           \nCIT.CG_ID_CITA_NUMERO = :IDCITA";

        public static final String AND_ESTADOS = " AND EC.EC_IDCODIGO = :ESTADO";
        public static final String AND_ESTADOS_NULL = " AND EC.EC_IDCODIGO IS NULL";
        public static final String AND_SEDE = " AND CA.CODIGOINTERNOCENTRO = :SEDE";
        public static final String AND_ESPECIALIDAD = " AND ESPE.SER_ESP_CODIGO = :ESPE";
        public static final String AND_SUBESPECIALIDAD = " AND SUBESPE.SER_SUB_CODIGO = :SUBESPE";
        public static final String AND_SERVICIO = " AND SER.SER_SER_CODIGO = :SERVICIO";
        public static final String AND_CONVENIO = " AND CONV.CON_CON_CODIGO IN (:CODCON)";
        public static final String AND_TIPO_DOCUMENTO = " AND TIP.TAB_TIPOIDENTCODIGO = :TIPIDENCOD";
        public static final String AND_NUMERO_DOCUMENTO = " AND TRIM(PAC.PAC_PAC_RUT) = :PAC";
        public static final String AND_NOMBRES = " AND UPPER(TRIM(PAC.PAC_PAC_NOMBRE)) LIKE (CONCAT('%', CONCAT(:NOMBRE, '%')))";
        public static final String AND_PRIMER_APPELLIDO = " AND UPPER(TRIM(PAC.PAC_PAC_APELLPATER)) LIKE (CONCAT('%', CONCAT(:APEPATER, '%')))";
        public static final String AND_SEGUNDO_APPELLIDO = " AND UPPER(TRIM(PAC.PAC_PAC_APELLMATER)) LIKE (CONCAT('%', CONCAT(:APEMATER, '%')))";
        public static final String AND_UBICACION_SEDE = " AND TRIM(AGEND.PCA_AGE_OBJETO) IN (:UBICACIONES)\n";
        public static final String AND_FECHAS = "AND CIT.CG_FECHA_PROCESO BETWEEN :FECHA_INICIAL AND :FECHA_FINAL\n";
        public static final String ORDERS_BY = " ORDER BY \"Fecha Cita\" desc,\n"
                + "         \"Hora Cita\" desc,\n"
                + "         \"Tipo de Documento homologado\" desc,\n"
                + "         \"Documento\" desc   \n";

        public static final String CONSULTAR_CITAS_POR_AUTORIZAR
                = "SELECT \n"
                + "CIT.CG_ID_CITA_NUMERO \"id_cita\",\n"
                + "PAC.PAC_PAC_NUMERO \"Pac numero\",TRIM(PAC.PAC_PAC_NOMBRE)||' '||TRIM(PAC.PAC_PAC_APELLPATER)||' '||TRIM(PAC.PAC_PAC_APELLMATER) \"Nombre Completo\",\n"
                + "TIP.TIPIDAV \"Tipo de Documento homologado\",\n"
                + "PAC.PAC_PAC_RUT \"Documento\",\n"
                + "CIT.PCA_AGE_FECHACITAC \"Fecha Cita\",\n"
                + "CIT.PCA_AGE_HORACITAC \"Hora Cita\",\n"
                + "CIT.CG_FECHA_PROCESO \"Fecha Cita CA\",\n"
                + "CIT.PCA_AGE_CODIGRECEP \"Cod user\", \n"
                + "CIT.CON_CON_CODIGO \"codigo convenio\",\n"
                + "CIT.PRE_PRE_CODIGO \"codigo prestacion\",\n"
                + "AUTCIT.PAC_PAC_NUMERO,\n"
                + "AUTCIT.GAU_AUTORIZA_SERV \"estadoProceso\", \n"
                + "(SELECT M.MOD_MOD_VALORPRES FROM ADMSALUD.NET_CONMODPREPRE@ISIS M\n"
                + "WHERE M.PRE_PRE_CODIGO = CIT.PRE_PRE_CODIGO AND M.MOD_MOD_PERIODOINI = CONV.MOD_MOD_PERIODOINI \n"
                + "AND M.MODELOTARIFCODIGO = CONV.MODELOTARIFCODIGO) \"valor_prestacional\", \n"
                + "CONV.CON_TIPOCONVECOD \"TipoConvenio\" \n"
                + "FROM            CA_CITAS_GESTIONADAS CIT\n"
                + "\n"
                + "INNER JOIN      ADMSALUD.PAC_PACIENTE@ISIS PAC\n"
                + "ON              TRIM(CIT.PAC_PAC_NUMERO)  = TRIM(PAC.PAC_PAC_NUMERO)\n"
                + "            \n"
                + "LEFT JOIN       ADMSALUD.CON_CONVENIO@ISIS CONV\n"
                + "ON              CIT.CON_CON_CODIGO = CONV.CON_CON_CODIGO\n"
                + "            \n"
                + "LEFT JOIN       ADMSALUD.TAB_TIPOIDENT@ISIS TIP\n"
                + "ON              TRIM(PAC.PAC_PAC_TIPOIDENTCODIGO) = TRIM(TIP.TAB_TIPOIDENTCODIGO)\n"
                + "            \n"
                /*+ "INNER JOIN      CA_ESTADOS_CITAS ESCIT\n"
                        + "ON                 CIT.EC_IDCODIGO = ESCIT.EC_IDCODIGO               \n"
                        + "\n"*/
                + "LEFT JOIN        CA_GESTION_AUTORIZACION_CITA AUTCIT\n"
                + "ON              AUTCIT.CG_ID_CITA_NUMERO = CIT.CG_ID_CITA_NUMERO \n"
                + "WHERE           \n"
                + "\n"
                + "((CIT.EC_IDCODIGO IN (2,7) AND AUTCIT.GAU_AUTORIZA_SERV = 3)\n"
                + "OR (CIT.EC_IDCODIGO IN (2)))";

        public static final String CONSULTAR_CITAS_POR_AUTORIZAR_EN_PROCESO = "SELECT \n"
                + "CIT.CG_ID_CITA_NUMERO \"id_cita\",\n"
                + "PAC.PAC_PAC_NUMERO \"Pac numero\","
                + "TRIM(PAC.PAC_PAC_NOMBRE)||' '||TRIM(PAC.PAC_PAC_APELLPATER)||' '||TRIM(PAC.PAC_PAC_APELLMATER) \"Nombre Completo\",\n"
                + "TIP.TIPIDAV \"Tipo de Documento homologado\",\n"
                + "PAC.PAC_PAC_RUT \"Documento\",\n"
                + "CIT.PCA_AGE_FECHACITAC \"Fecha Cita\",\n"
                + "CIT.PCA_AGE_HORACITAC \"Hora Cita\",\n"
                + "CIT.CG_FECHA_PROCESO \"Fecha Cita CA\",\n"
                + "CIT.PCA_AGE_CODIGRECEP \"Cod user\", \n"
                + "CIT.CON_CON_CODIGO \"codigo convenio\",\n"
                + "CIT.PRE_PRE_CODIGO \"codigo prestacion\", "
                + "AUTCIT.PAC_PAC_NUMERO,\n"
                + "AUTCIT.GAU_AUTORIZA_SERV \"estadoProceso\" "
                + "FROM            CA_CITAS_GESTIONADAS CIT\n"
                + "\n"
                + "INNER JOIN      ADMSALUD.PAC_PACIENTE@ISIS PAC\n"
                + "ON              TRIM(CIT.PAC_PAC_NUMERO)  = TRIM(PAC.PAC_PAC_NUMERO)\n"
                + "            \n"
                + "LEFT JOIN       ADMSALUD.TAB_TIPOIDENT@ISIS TIP\n"
                + "ON              TRIM(PAC.PAC_PAC_TIPOIDENTCODIGO) = TRIM(TIP.TAB_TIPOIDENTCODIGO)\n"
                + "            \n"
                + "INNER JOIN      CA_ESTADOS_CITAS ESCIT\n"
                + "ON \t\tCIT.EC_IDCODIGO = ESCIT.EC_IDCODIGO               \n"
                + "INNER JOIN        CA_GESTION_AUTORIZACION_CITA AUTCIT\n"
                + "ON              AUTCIT.CG_ID_CITA_NUMERO = CIT.CG_ID_CITA_NUMERO "
                + "\n"
                + "WHERE           \n"
                + "\n"
                + "CIT.EC_IDCODIGO = 7 AND CIT.PCA_AGE_FECHACITAC BETWEEN :FECHAINICIAL AND :FECHAFINAL AND AUTCIT.GAU_AUTORIZA_SERV = 3 ";

        public static final String ORDERS_BY_CITAS_POR_AUTORIZAR = " ORDER BY \n"
                + "         \"Fecha Cita CA\" desc \n";
    }

    public static class OrdenesMedicas {

        public static final String CONSULTAR_ORDENES = "SELECT DISTINCT \n"
                + "COM.ORM_ID_ORDM_NUMERO \"Id\",\n"
                + "COM.CG_FECHA_PROCESO \"Fecha y hora abordaje derivacion\",\n"
                + "TIP.TIPIDAV \"Tipo doc\",\n"
                + "PAC.PAC_PAC_RUT \"Numero doc\",\n"
                + "TRIM (PAC.PAC_PAC_NOMBRE)||' '||TRIM(PAC.PAC_PAC_APELLPATER)||' '||TRIM(PAC.PAC_PAC_APELLMATER) \"Nombre Completo\",\n"
                + "(SELECT COUNT(*) FROM CA_GESTION_AUTORIZACION WHERE POM_ID_PREST_ORDM IN (\n"
                + "SELECT POM_ID_PREST_ORDM FROM CA_PRESTACIONES_ORDMED WHERE ORM_ID_ORDM_NUMERO = cpo.orm_id_ordm_numero)\n"
                + "AND GAU_AUTORIZA_SERV = 3) enProceso,\n"
                + "(SELECT COUNT(*) FROM CA_GESTION_AUTORIZACION WHERE POM_ID_PREST_ORDM IN (\n"
                + "SELECT POM_ID_PREST_ORDM FROM CA_PRESTACIONES_ORDMED WHERE ORM_ID_ORDM_NUMERO = cpo.orm_id_ordm_numero)\n"
                + "AND GAU_AUTORIZA_SERV = 1) autorizada,"
                + "CPO.* \n"
                + "FROM CA_ORDENES_MEDICAS COM \n"
                + "LEFT JOIN (SELECT DISTINCT count(cpo.orm_id_ordm_numero) AS prestaciones,\n"
                + "cpo.orm_id_ordm_numero, count(gco.continuidad) AS continuidad\n"
                + "FROM CA_PRESTACIONES_ORDMED cpo\n"
                + "LEFT JOIN (SELECT DISTINCT count(gco.GCO_REALIZO_AGENDAMIENTO) AS continuidad, gco.pom_id_prest_ordm\n"
                + "FROM CA_TRAZA_GEST_CONTINUIDAD gco\n"
                + "WHERE gco.GCO_REALIZO_AGENDAMIENTO = 1\n"
                + "GROUP BY gco.pom_id_prest_ordm) gco\n"
                + "ON cpo.pom_id_prest_ordm = gco.pom_id_prest_ordm\n"
                + "GROUP BY cpo.orm_id_ordm_numero) cpo\n"
                + "ON com.orm_id_ordm_numero = cpo.orm_id_ordm_numero\n"
                + "LEFT JOIN ADMSALUD.PAC_PACIENTE@ISIS pac\n"
                + "ON com.pac_pac_numero = pac.pac_pac_numero\n"
                + "LEFT JOIN ADMSALUD.TAB_TIPOIDENT@ISIS tip\n"
                + "ON TRIM(pac.PAC_PAC_TIPOIDENTCODIGO) = TRIM(tip.TAB_TIPOIDENTCODIGO)\n"
                + "WHERE COM.CG_FECHA_PROCESO BETWEEN :FECHAINICIAL AND :FECHAFINAL \n";
        ;

        public static final String AND_ESTADOS = " AND (SELECT MAX(TRA.EOM_IDCODIGO) FROM CA_TRAZA_ORDENMEDICAS TRA WHERE TRA.ORM_ID_ORDM_NUMERO = COM.ORM_ID_ORDM_NUMERO) IN (:ESTADOS)\n";

        public static final String ORDERS_BY = " ORDER BY com.cg_fecha_proceso\n";
    }

    public static class Listas {

        public static final String CONSULTAR_SEDES = "SELECT CODIGOINTERNOCENTRO, TRIM(NOMBRECENTROATEN), CODIGOCENTROATEN FROM ADMSALUD.TAB_CENTROSATENC@ISIS ORDER BY NOMBRECENTROATEN";
        public static final String CONSULTAR_CONVENIOS = "SELECT CON_CON_CODIGO, TRIM(CON_CON_DESCRIPCIO), CON_CON_TIPOCONVE FROM ADMSALUD.CON_CONVENIO@ISIS ORDER BY CON_CON_DESCRIPCIO";
        public static final String CONSULTAR_POLIZAS = "SELECT PAC_PAC_NUMERO, ACC_ID_NUMERO, EC_POLIZA_NUMERO, PCA_AGE_CODIGRECEP, CG_FECHA_PROCESO FROM CA_POLIZAS_PACIENTES";
        public static final String CONSULTAR_ESPECIALIDADES = "SELECT SER_ESP_CODIGO, TRIM(SER_ESP_DESCRIPCIO), SER_ESP_CODIGO OTRO FROM ADMSALUD.SER_ESPECIALI@ISIS ORDER BY SER_ESP_DESCRIPCIO";
        public static final String CONSULTAR_CITASAUTORIZADAS = "SELECT\n"
                + "CCG.CG_ID_CITA_NUMERO COD_ID_CITA,\n"
                + "CCG.PAC_PAC_NUMERO COD_PAC_NUMERO,\n"
                + "CCG.PCA_AGE_CODIGPROFE COD_CODIGPROFE,\n"
                + "CCG.EC_IDCODIGO COD_IDCODIGO,\n"
                + "TIP.TIPIDAV Tipo_Documento_homologado,\n"
                + "PAC.PAC_PAC_RUT Documento,\n"
                + "TRIM(PAC.PAC_PAC_NOMBRE)||' '||TRIM(PAC.PAC_PAC_APELLPATER)||' '||TRIM(PAC.PAC_PAC_APELLMATER) Nombre_Completo,\n"
                + "CITZ.GAU_CODIGO_AUTORIZACION as codigoAutorizacion,\n"
                + "CITZ.GAU_VALOR_PRESTACION as valorPrestacion,\n"
                + "TRUNC(CCG.PCA_AGE_FECHACITAC) as fechaCita, \n"
                + "CCG.PCA_AGE_HORACITAC as horaCita, \n"
                + "TRUNC(CITZ.GAU_FECHA_AUTORIZACION) fechautorizacion\n"
                + "FROM CA_CITAS_GESTIONADAS CCG,\n"
                + "ADMSALUD.PAC_PACIENTE@ISIS PAC,\n"
                + "ADMSALUD.TAB_TIPOIDENT@ISIS TIP,\n"
                + "CA_GESTION_AUTORIZACION_CITA CITZ \n"
                + "WHERE CCG.EC_IDCODIGO = 3\n"
                + "AND       TRIM(CCG.PAC_PAC_NUMERO)  = TRIM(PAC.PAC_PAC_NUMERO)\n"
                + "AND       TRIM(PAC.PAC_PAC_TIPOIDENTCODIGO) = TRIM(TIP.TAB_TIPOIDENTCODIGO)\n"
                + "AND CITZ.CG_ID_CITA_NUMERO = CCG.CG_ID_CITA_NUMERO \n"
                + "ORDER BY CITZ.GAU_FECHA_AUTORIZACION desc";
        public static final String CONSULTAR_SUBESPECIALIDADES = "SELECT SER_SUB_CODIGO, TRIM(SER_SUB_DESCRIPCIO), SER_ESP_CODIGO FROM ADMSALUD.SER_SUBESPECIA@ISIS ORDER BY SER_SUB_DESCRIPCIO";
        public static final String CONSULTAR_SERVICIOS = "SELECT\n"
                + "SER.SER_SER_CODIGO COD_SERVICIO,\n"
                + "SER.SER_SER_DESCRIPCIO SERVICIO,\n"
                + "SER.SER_SER_CODSUBESPE COD_SUBESPE,\n"
                + "SER.SER_SER_CODIGESPEC COD_ESPE\n"
                + "FROM ADMSALUD.SER_SERVICIOS@ISIS SER,\n"
                + "ADMSALUD.SER_ESPECIALI@ISIS ESPE,\n"
                + "ADMSALUD.SER_SUBESPECIA@ISIS SUBESPE\n"
                + "WHERE SER.SER_SER_CODIGESPEC = ESPE.SER_ESP_CODIGO\n"
                + "AND SER.SER_SER_CODSUBESPE= SUBESPE.SER_SUB_CODIGO\n"
                + "AND SUBESPE.SER_ESP_CODIGO=ESPE.SER_ESP_CODIGO\n"
                + "ORDER BY SER.SER_SER_DESCRIPCIO";
        public static final String CONSULTAR_MEDICOS = "SELECT SER_PRO_RUT, TRIM(SER_PRO_NOMBRES)||' '||TRIM(SER_PRO_APELLPATER)||' '||TRIM(SER_PRO_APELLMATER) NOMBRE, SER_PRO_TIPOIDENT FROM ADMSALUD.SER_PROFESIONA@ISIS WHERE SER_PRO_ESTADO='A' ORDER BY NOMBRE";
        public static final String CONSULTAR_MOTIVOS_NO_AUTORIZA = "SELECT MNA_IDCODIGO, MNA_DESCRIPCION, MNA_ESTADO FROM CA_MOTIVOS_NO_AUTORIZACION WHERE MNA_ESTADO = '1'";
        public static final String CONSULTA_UBICACION_SEDES = "select distinct ubicacion as ub1, ubicacion as ub2, '' as ub3 from ca_ubicacion_sedes where ubicacion is not null";

    }
}
